plugins = []
functionsDirectory = "C:\\Users\\juand\\OneDrive\\Desktop\\Workshido\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\juand\\OneDrive\\Desktop\\Workshido"
publishOrigin = "default"
functions = "C:\\Users\\juand\\OneDrive\\Desktop\\Workshido\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]